/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht291.nim.component;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class ButtonNim extends javax.swing.JPanel{

    /**
     * Creates new form ButtonNim
     */
    public ButtonNim() {
        initComponents();
        buttonNim.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNim = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(60, 60));

        buttonNim.setBackground(new java.awt.Color(204, 204, 204));
        buttonNim.setForeground(new java.awt.Color(102, 102, 102));
        buttonNim.setAlignmentY(0.0F);
        buttonNim.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonNim.setMaximumSize(new java.awt.Dimension(55, 55));
        buttonNim.setMinimumSize(new java.awt.Dimension(55, 55));
        buttonNim.setPreferredSize(new java.awt.Dimension(55, 55));
        buttonNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNimActionPerformed

    }//GEN-LAST:event_buttonNimActionPerformed

    public JButton getButtonNim() {
        return buttonNim;
    }

    public void setButtonNim(JButton buttonNim) {
        this.buttonNim = buttonNim;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNim;
    // End of variables declaration//GEN-END:variables
 
    


}
