/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht291.nim.component;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class ModeGameBtn extends javax.swing.JPanel {

    /**
     * Creates new form ModeGameBtn
     */
    
    public ModeGameBtn() {
        initComponents();
        
        btnWithBOT.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnBOT_black.png")));
        btnWithPlayer.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnPlayer_black.png")));
        
        btnWithBOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithBOT.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnBOT_red.png")));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWithBOT.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnBOT_black.png")));
            }
        });

        btnWithPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithPlayer.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnPlayer_red.png")));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWithPlayer.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/btnPlayer_black.png")));
            }
        });

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWithBOT = new javax.swing.JButton();
        btnWithPlayer = new javax.swing.JButton();

        setOpaque(false);

        btnWithBOT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithBOT.setPreferredSize(new java.awt.Dimension(290, 70));
        btnWithBOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithBOTActionPerformed(evt);
            }
        });

        btnWithPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithPlayer.setPreferredSize(new java.awt.Dimension(290, 70));
        btnWithPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithPlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWithBOT, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btnWithPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithBOT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithBOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithBOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWithBOTActionPerformed

    private void btnWithPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWithPlayerActionPerformed

    public JButton getBtnWithBOT() {
        return btnWithBOT;
    }

    public JButton getBtnWithPlayer() {
        return btnWithPlayer;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWithBOT;
    private javax.swing.JButton btnWithPlayer;
    // End of variables declaration//GEN-END:variables
}
