/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht291.nim.component;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class PlayerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel() {
        initComponents();
        
        playerTop.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/player1_black.png")));
        playerBottom.setIcon(new ImageIcon(getClass().getResource("/ht291/nim/data/player2_black.png")));
        
        playerBottom.setBorderPainted(false);
        playerTop.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerBottom = new javax.swing.JButton();
        playerTop = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);

        playerBottom.setPreferredSize(new java.awt.Dimension(201, 58));
        playerBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerBottomActionPerformed(evt);
            }
        });

        playerTop.setPreferredSize(new java.awt.Dimension(201, 58));
        playerTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playerBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerBottomActionPerformed

    private void playerTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerTopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton playerBottom;
    private javax.swing.JButton playerTop;
    // End of variables declaration//GEN-END:variables

    public JButton getPlayerBottom() {
        return playerBottom;
    }

    public JButton getPlayerTop() {
        return playerTop;
    }

}
